#!/usr/bin/env bash
#MISE description="Build the project"
#MISE depends=["setup"]
#MISE sources=["src/**/*"]
#MISE outputs=["dist/index.js"]

bun build ./src/index.ts --outdir dist --target bun --format esm --packages external \
	--external '@mariozechner/pi-coding-agent' \
	--external '@mariozechner/pi-tui' \
	--external '@mariozechner/pi-ai'
